name: Node Js App Deployment using workflows CICD
on:
    push: 
        branches: [master]

permissions:
    contents: write

jobs:
    Build_And_Deploy:

        runs-on: [ubuntu-latest]
        steps:
            - name: Checkout Resource
              uses: actions/checkout@v3

            - name: Install Node JS
              uses: actions/setup-node@v3
              with:
                node-version: 18

            - name: Install dependencies
              run: npm install

            - name: Build Project
              run: npm run build
              env:
                REACT_APP_WELCOME_TXT: ${{vars.REACT_APP_WELCOME_TXT}}

            - name: Deploy to Github pages
              uses: JamesIves/github-pages-deploy-action@4.1.0
              with:
                branch: gh-pages
                folder: build